name: all_in_one_flutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flick_video_player: ^0.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  go_router: ^13.2.0
  intl: ^0.19.0
  riverpod_annotation: ^2.3.4
  video_player: ^2.8.2

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.4.1
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
